config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root to: 'articles#index', :as => :home
  delete 'images', to: 'images#destroy', :as => :image_destroy
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  #paginator configuration
  paginates_per 6

  #table fields
  field :title, type: String
  field :content, type: String

  #articles indexing
  index({ created_at: 1 }, { background: true })

  #reference to images, that compilance specific article
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, :allow_destroy => true

  #set index name
  index_name "articles-#{Rails.env}"

  #makes serialization
  def as_indexed_json (options={})
    as_json(except: [:id, :_id])
  end


  #search parameters
  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['title^10', 'text', 'content^10', 'text']
          }
        },
        size: 30
      }
    )
  end
end

app/models/image.rb
class Image
  include Mongoid::Document
  include Mongoid::Paperclip

  #reference many images to specific article
  belongs_to :article

  #set images attributes
  has_mongoid_attached_file :image,
      :url => "/:attachment/:id/:style/:filename",
      :styles => {
        :original => ['1920x1680>', :jpg],
        :medium   => ['250x250',    :jpg]
      }

  #set image validation
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png image/gif)
end

app/models/user.rb
class User
  include Mongoid::Document
  
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :rights,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    #check admin or ordinary user
    def checking_rights
      if user_signed_in? and current_user.rights != 'admin'
        redirect_to :home
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #find specific article
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  #validate user 'has admin rights or not'
  before_action :checking_rights, only: [:edit, :create, :update, :destroy, :new]

  #main page
  def index
    #search parameters
    if params[:search]
      @articles = Article.search(params[:search]).records.order_by(created_at: :desc).page params[:page]
    else
      @articles = Article.order_by(created_at: :desc).page params[:page]
    end
  end

  def new
    @article = Article.new
    respond_to :html
  end

  def create
    #getting parameters from request
    @article = Article.new(article_params)
    
    #adding images if they has been added in request form
    if params[:article][:image]
      params[:article][:image].each do |image_item| 
        @article.images.build(image: image_item)
      end
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to home_path, notice: 'Статья успешно создана.' }
      else
        format.json { render json: @article.errors }
      end
    end
  end

  def update
    #adding images to existing article if they has been added in request form
    if params[:article][:image]
      params[:article][:image].each do |image_item| 
        @article.images.push(Image.new(image: image_item))
      end
    end

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Статья успешно обновлена.' }
      else
        format.json { render json: @article.errors }
      end
    end
  end

  def destroy
    #delete specific article and her images
    @article.destroy
    respond_to :js
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  #validate user 'has admin rights or not'
  before_action :checking_rights, only: [:destroy]
  
  #destroy specific image
  def destroy
    if (params[:image_id])
      Image.where(_id: params[:image_id]).destroy
    end
  end
end

app/views/articles/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="form" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><%= header %></h4>
      </div>
      <div class="modal-body">

        <!-- Начало формы запроса -->
        <%= form_with(model: article, local: false, html: { multipart: :true }) do |form| %>
          <% if article.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(article.errors.count, "error") %> не удалось сохранить статью:</h2>

              <ul>
              <% article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :Заголовок %>
            <%= form.text_field :title, id: :article_title, size: 41 %>
          </div>

          <div class="field">
            <%= form.label :Cодержание %>
            <%= form.text_area :content, id: :article_content, cols: 40, rows: 10 %>
          </div>

          <% unless @article.images.nil? %>
            <div class="field">
              <% @article.images.each do |image_item| %>
                <div>
                  <%= link_to 'Удалить', image_destroy_path(image_id: image_item.id), method: :delete, remote: true, class: :delete_image %>
                  <%= image_tag image_item.image.url(:medium), id: image_item.id %>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="field">
            <br>
            <%= form.file_field :image, id: :article_image, multiple: true %>
          </div>

          <div class="actions">
            <%= form.submit 'Сохранить', class: :save_article %>
          </div>
        <% end %>
        <!-- Конец формы запроса -->

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn alt" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
    
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article, header: 'Редактирование статьи' %>

app/views/articles/index.html.erb
<div class="row">
  <div class="12u">

    <!-- Search form -->
    <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
      <div class="form-group">
        <div class="input-group input-group-lg col-lg-12 col-centered">
          <%= text_field_tag :search, params[:search], placeholder: "Искомый запрос", class: 'form-control' %>
          <span class="input-group-btn">
            <%= button_tag "Поиск", class: 'btn button alt' %>
          </span>
        </div>
      </div>
    <% end %>

    <!-- News -->
    <section>
      <header class="major">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
            <%= paginate @articles, window: 2 %>
          </div>
        </div>
      </header>
      <% @articles.each do |article| %>

        <% count = cycle('odd', 'even') %>

        <!-- checking even or odd article in the sequence, for creating new "two-article" row -->
        <% if count == 'odd' %>
          <div class="row">
        <% end %>

        <div class="6u 12u(mobile)">
          <section class="box">
            <a href="<%= article_path(article) %>" class="image featured">
              <% if article.images[0] %>
                <div class='news-images' style="background-image: url('<%= article.images[0].image.url(:original) %>')" "></div>
              <% else %>
                <%= image_tag 'default.jpg', width: 451, height: 241 %>
              <% end %>
            </a>
            <header>
              <!-- check has title or not for defaulting him -->
              <% if article.title != '' %>
                <h3><%= article.title %></h3>
              <% else %>
                <h3>Здесь мог быть заголовок</h3>
              <% end %>
            </header>
              <!-- check has content or not for defaulting him -->
              <% if article.content != '' %>
                <!-- show preview content -->
                <p><%= article.content[0..88] %>...</p>
              <% else %>
                <p>Здесь мог быть текст</p>
              <% end %>
            <footer>
              <ul class="actions">
                <li><%= link_to 'Читать', article_path(article), class: 'button alt' %></li>
                <% if user_signed_in? and current_user.rights == 'admin' %>
                  <li><%= link_to 'Редактировать', edit_article_path(article), remote: true, class: 'get_form button alt' %></li>
                  <li><%= link_to 'Удалить', article, method: :delete, remote: true, class: 'delete_entry button' %></li>
                <% end %>
              </ul>
            </footer>
          </section>
        </div>

        <!-- checking even or odd article in the sequence, for creating new "two-article" row -->
        <% if count == 'even' %>
          </div>
        <% end %>

      <% end %>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
          <%= paginate @articles, window: 2 %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article, header: 'Создание статьи' %>

app/views/articles/show.html.erb
<!-- Main -->
<div id="main-wrapper">
  <div class="container">

    <!-- Start of article -->
    <article class="box post">
      <% if @article.images[0] %>
        <a class="image featured"><%= image_tag @article.images[0].image.url(:original) %></a>
      <% else %>
        <a class="image featured"><%= image_tag 'default.jpg' %></a>
      <% end %>
      <header>
        <h2><%= @article.title %></h2>
      </header>
      <p>
        <%= @article.content %>
      </p>
      <% if @article.images.count > 1 %>
        <section>
          <header>
            <h3>Дополнительные изображения</h3>
          </header>
          <p>
            <% @article.images.each do |image_item| %>
              <%= image_tag image_item.image.url(:medium) %>
            <% end %>
          </p>
        </section>
      <% end %>
    </article>
    <!-- End of article -->

  </div>
</div>

<% if user_signed_in? and current_user.rights == 'admin' %>
  <%= link_to 'Редактировать', edit_article_path(@article), remote: true, class: 'get_form button' %>
<% end %>
<%= link_to 'К списку новостей', home_path, class: 'button alt' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Новостное агентство bom-bom</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
  </head>
  <% unless notice.nil? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% unless alert.nil? %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <body class="homepage">
    <div id="page-wrapper">

      <!-- Header -->
      <div id="header-wrapper">
        <div id="header">

          <!-- Logo -->
          <h1><%= link_to 'RAIL\'S //', home_path %></h1>

          <!-- Nav -->
          <nav id="nav">
            <ul>
              <li><%= link_to 'Главная', home_path %></li>
              <li>
                <% if user_signed_in? and current_user.rights == 'admin' %>
                  <% if current_page?(home_path) or current_page?(articles_path) %>
                    <td><%= link_to 'Создать статью', new_article_path(@article), remote: true, format: :html, class: :get_form %></td>
                  <% end %>
                <% end %>
              </li>

              <% if user_signed_in? %>
                <li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <% unless request.url.match('sign_in') or request.url.match('sign_up') %>
                  <li><%= link_to "Регистрация", new_user_registration_path %></li>
                  <li><%= link_to "Вход", new_user_session_path %></li>
                <% end %>
              <% end %>
            </ul>
          </nav>

        </div>
      </div>

      <!-- Main -->
      <div id="main-wrapper">
        <div class="container">

          <%= yield %>

        </div>
      </div>

      <!-- Footer -->
      <div id="footer-wrapper">
        <section id="footer" class="container">
          <div class="row">
            <div class="12u">

              <!-- Copyright -->
              <div id="copyright">
                <ul class="links">
                  <li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                </ul>
              </div>

            </div>
          </div>
        </section>
      </div>
    </div>

    <!-- Ajax response -->
    <div id="results"></div>

  </body>
</html>